### ISSUE TITLE
Unintuitive side panel placement

### ISSUE THREAD

**Issue by pablothedolphin** [speckleworks/speckle-website#26]
Most web sites, including the speckle viewer, have the navigation panel on the left hand side but the main speckle web site keeps it on the right. Is there a reason for this? If not I would suggest moving it to the left since I think that's what most people are used to.

**Comment by didimitrie** [comment]
Yep, there is a reason: moving the docs panel on the left side would mean that the hamburger menu conflicts with the logo used for the home button. 

Generally, it's fine, but we try to avoid cosmetic PRs/issues - so I'll close this for now!
