### ISSUE TITLE
Netlify "page not found" error when trying to view site

### ISSUE THREAD

**Issue by tluth** [speckleworks/speckle-website#45]
Ruh rohhh

![image](https://user-images.githubusercontent.com/35136057/81684928-bd774f80-9457-11ea-9899-fa97666e67dd.png)

**Comment by didimitrie** [comment]
reverted bad build, is it working now? (looks good to me...)

**Comment by tluth** [comment]
Yeah working now! GOD DAM YOU ARE QUICK DIMITIRIE

**Comment by didimitrie** [comment]
@netlify makes it easy - all kudos to them :)
